### ISSUE TITLE
Error while "truffle deploy"

### ISSUE THREAD

**Issue by rajjha** [blocktix/blocktix#1]
$ truffle deploy
Using network 'development'.

Error: Could not find built Migrations contract: Could not find artifacts for ./Migrations.sol from any sources
    at Object.lastCompletedMigration (C:\Users\raj.jha\AppData\Roaming\npm\node_modules\truffle\node_modules\truffle-migrate\index.js:195:23)
    at Object.needsMigrating (C:\Users\raj.jha\AppData\Roaming\npm\node_modules\truffle\node_modules\truffle-migrate\index.js:218:10)
    at C:\Users\raj.jha\AppData\Roaming\npm\node_modules\truffle\lib\commands\migrate.js:41:19
    at C:\Users\raj.jha\AppData\Roaming\npm\node_modules\truffle\lib\environment.js:67:9
    at C:\Users\raj.jha\AppData\Roaming\npm\node_modules\truffle\node_modules\web3\lib\web3\property.js:119:13
    at C:\Users\raj.jha\AppData\Roaming\npm\node_modules\truffle\node_modules\web3\lib\web3\requestmanager.js:89:9
    at XMLHttpRequest.request.onreadystatechange (C:\Users\raj.jha\AppData\Roaming\npm\node_modules\truffle\node_modules\web3\lib\web3\httpprovider.js:118:13)
    at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\raj.jha\AppData\Roaming\npm\node_modules\truffle\node_modules\xhr2\lib\xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (C:\Users\raj.jha\AppData\Roaming\npm\node_modules\truffle\node_modules\xhr2\lib\xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (C:\Users\raj.jha\AppData\Roaming\npm\node_modules\truffle\node_modules\xhr2\lib\xhr2.js:509:12)

**Comment by rajjha** [comment]
Not an Issue as prototype is not complete. Retracting issue.
